# Generated by Django 2.2.4 on 2019-09-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190901_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='profile_pics'),
        ),
    ]
